version: '3'

services:
  influxdb:
    image: influxdb:2.1-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - grafana-data:/etc/ssl/elterontech
      - /etc/ssl/elterontech:/etc/ssl/elterontech
      - influxdb-data:/var/lib/influxdb2
